GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/5

###
DELETE http://localhost:3001/api/persons/4

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Naoi Rei",
    "number": "444-444-4444"
}

###
GET http://localhost:3001/api/persons/6647af36353f36f4338c6ae5